export const menus = [
   {
      key: 1,
      label: "Apps",
      type: "label",
   },
   {
      key: 2,
      label: "Dashboard",
      icon: "iconoir:home-simple",
      link: "/apps/dashboard",
      type: "item",
   },
   {
      key: 3,
      label: "Ticket",
      type: "label",
   },
   {
      key: 4,
      label: "Ticket List",
      icon: "bi:ticket-perforated",
      link: "/ticket/list",
      type: "item",
   },
   {
      key: 5,
      label: "Ticket Category",
      icon: "iconoir:bookmark-empty",
      link: "/ticket/analytics",
      type: "item",
   },
   {
      key: 6,
      label: "CRM",
      type: "label",
   },
   {
      key: 7,
      label: "Custumer Data",
      link: "/customer",
      icon: "iconoir:verified-user",
      type: "item",
   },
   {
      key: 8,
      label: "Human Resource",
      type: "label",
   },
   // {
   //    key: 9,
   //    label: "Employees",
   //    link: "/employees",
   //    icon: "ion:briefcase-outline",
   //    type: "item",
   // },
   {
      key: 10,
      label: "Shifting",
      link: "/shifting",
      icon: "uil:schedule",
      type: "item",
   },
   {
      key: 11,
      label: "Manage",
      type: "label",
   },
   {
      key: 12,
      label: "Company",
      link: "/manage/company",
      icon: "fluent:building-24-regular",
      type: "item",
   },
   {
      key: 13,
      label: "User Management",
      link: "/manage/users",
      icon: "iconoir:group",
      type: "item",
   },
   {
      key: 14,
      label: "Billings",
      link: "/manage/billing",
      icon: "icon-park-outline:bill",
      type: "item",
   },
   {
      key: 15,
      label: "SMTP",
      link: "/manage/smtp",
      icon: "icon-park-outline:bill",
      type: "item",
   },
   // {
   //    key: 16,
   //    label: "Email Template",
   //    link: "/manage/template",
   //    icon: "fluent:mail-template-24-regular",
   //    type: "item",
   // },
];
